### ISSUE TITLE
Plans for recent Python and Spark versions

### ISSUE THREAD

**Issue by khaledh** [mattjw/sparkql#103]
It looks like the library's dependencies haven't been updated in a while. We're currently using Python 3.9/3.10 and Spark 3.3. Is there any plans to update the dependencies to work with more recent versions?

**Comment by mattjw** [comment]
@khaledh thanks again for the feature request, and even more so for doing the hard work of upgrading the library.

v0.6.0 is now released:

- pypi: https://pypi.org/project/sparkql/0.6.0/
- https://github.com/mattjw/sparkql/releases/tag/v0.6.0

It's great to hear there's someone out there who might find this package useful. Any future feature request or collaborations very welcome. As I'm not using PySpark right now, if there's something else out there who wants to take a closer role in steering this, I'm very open to it.
